#!/usr/bin/env ruby
require 'fileutils'

ENVIRONMENT_BASEDIR = "/etc/puppet/environments"
SOURCE_REPOSITORY = File.expand_path(ENV['GIT_DIR'])

ENV.delete('GIT_DIR')

unless File.directory? ENVIRONMENT_BASEDIR
  puts %Q{#{ENVIRONMENT_BASEDIR} does not exist, cannot create environment directories.}
  exit 1
end

$stdin.each_line do |line|
  oldrev, newrev, refname = line.split(" ")

  # Determine the branch name from the refspec we're received, which is in the
  # format refs/heads/, and make sure that it doesn't have any possibly
  # dangerous characters
  branchname = refname.sub(%r{^refs/heads/(.*$)}) { $1 }
  if branchname =~ /[\W-]/
    puts %Q{Branch "#{branchname}" contains non-word characters, ignoring it.}
    next
  end

  environment_path = "#{ENVIRONMENT_BASEDIR}/#{branchname}"

  if File.directory? environment_path
    Dir.chdir environment_path
    if File.file? "Puppetfile"
      puts "Cleaning modules via librarian-puppet"
      puts "%{oldrev}-${newrev}"
      %x{librarian-puppet clean}
    end
  end
end
