#!/bin/bash

ENVIRONMENT_STR=""
if (( $# == 1 )); then
  ENVIRONMENT_STR="--environment ${1}"
fi

sudo puppet agent --verbose --no-daemonize --onetime --no-splay --detailed-exitcodes ${ENVIRONMENT_STR}

exit $?
